"""add order_reports table

Revision ID: 267d2da9733d
Revises: 2b004bb2a258
Create Date: 2025-12-16 20:03:08.202086

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '267d2da9733d'
down_revision: Union[str, Sequence[str], None] = '2b004bb2a258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "order_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_at", sa.Date(), nullable=False),
        sa.Column("order_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("count_product", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_order_reports_id"), "order_reports", ["id"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_reports_id'), table_name='order_reports')
    op.drop_table('order_reports')
    # ### end Alembic commands ###
